version: '3.8'
services:
  backend:
    build: ./backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./backend/models:/app/models
    environment:
      # Stripe-переменные временно отключены
      # - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      # - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - QWEN_MODEL_PATH=/app/models/qwen-model_full
      - FAISS_INDEX_PATH=/app/data/index.faiss
      - FAISS_META_PATH=/app/data/index.faiss.meta
      - CUDA_VISIBLE_DEVICES=""
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    command: uvicorn app:app --host 0.0.0.0 --port 8000