apiVersion: v1
kind: Service
metadata:
  name: ai-model-service
  namespace: rag-system
  labels:
    app: ai-model
spec:
  selector:
    app: ai-model
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model-deployment
  namespace: rag-system
  labels:
    app: ai-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
      - name: ai-model
        image: rag-ai-model:latest
        imagePullPolicy: Never  # Для локальной разработки
        ports:
        - containerPort: 8003
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: REDIS_URL
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: MODEL_PATH
        - name: DEVICE
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: DEVICE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "10Gi"
            cpu: "6"
        volumeMounts:
        - name: models-storage
          mountPath: /app/models
        - name: logs-storage
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: models-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: logs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: rag-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: rag-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 